USB_VID = 0x239A
USB_PID = 0x80DC
USB_PRODUCT = "Wooof Pet Health Monitor"
USB_MANUFACTURER = "Wooof"

MCU_CHIP = nrf52840

# Use SoftDevice S140 v7.0.1 (default is 6.1.0)
SOFTDEV_VERSION = 7.0.1

CIRCUITPY_USB = 0
INTERNAL_FLASH_FILESYSTEM = 1

CIRCUITPY_CREATOR_ID = 0x12345679
CIRCUITPY_CREATION_ID = 0x87654322

# Enable features needed for pet monitoring
CIRCUITPY_BLEIO = 1
CIRCUITPY_AUDIOBUSIO = 1
CIRCUITPY_BUSIO = 1
CIRCUITPY_SUPERVISOR = 1
CIRCUITPY_ALARM = 1
CIRCUITPY_DIGITALIO = 1
CIRCUITPY_MICROCONTROLLER = 1

# Optimize for memory constrained device
CIRCUITPY_DISPLAYIO = 0
CIRCUITPY_FRAMEBUFFERIO = 0
CIRCUITPY_VECTORIO = 0
CIRCUITPY_NEOPIXEL_WRITE = 0
CIRCUITPY_PULSEIO = 0
CIRCUITPY_RGBMATRIX = 0
